name: Atata
short_description: "C#/.NET test automation framework"

# Dependencies
markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: false

gems:
  - jekyll-sitemap

# Permalinks
permalink: pretty

author:
  name: Yevgeniy Shunevych
  github: YevgeniyShunevych

baseurl: ""
url: ""

nav_links:
  Getting Started: "getting-started"
  Components: "components"
  Finding: "finding"
  Triggers: "triggers"
  Advanced: "advanced"

getting-started:
  - name: Introduction
  - name: Demo
  - name: Usage
  - name: Logging

components:
  - name: Base
    items:
      - UIComponent
      - Control
      - PageObject
      - Page
      - PopupWindow
  - name: Inputs
    items:
      - TextInput
      - PasswordInput
      - NumberInput
      - DateInput
      - TimeInput
  - name: Select
  - name: CheckBox
  - name: CheckBoxList
  - name: RadioButton
  - name: RadioButtonList
  - name: TextArea
  - name: Button
  - name: Link
  - name: Clickable
  - name: Table
  - name: Content
    items:
      - Enum Content
      - Text
      - Number
      - H1-H6

finding:
  - name: Terms
    items:
      - TermMatch
      - TermCase
      - Multiple Terms
  - name: Find Attributes
    items:
      - FindById
      - FindByName
      - FindByClass
  - name: TermFindSettings

triggers:
  - name: VerifyTitle
  - name: VerifyContent
  - name: VerifyContentMatches
  - name: Wait
  - name: LogInfo

exclude:
  - LICENSE
  - README.md
  - atata-framework.github.io.sln
  - compilerconfig.json
  - compilerconfig.json.defaults
  - .gitignore

links:
    atata_github: https://github.com/atata-framework/atata
    atata_nuget: https://www.nuget.org/packages/Atata
    atata_webdriverextras_nuget: https://www.nuget.org/packages/Atata.WebDriverExtras