name: Atata
short_description: "C#/.NET test automation framework"

# Dependencies
markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: false

# Permalinks
permalink: pretty

author:
  name: Yevgeniy Shunevych
  github: YevgeniyShunevych

baseurl: ""
url: ""

nav_links:
  Getting Started: "getting-started"
  Components: "components"
  Finding: "finding"
  Triggers: "triggers"
  Advanced: "advanced"

getting_started:
  - Introduction
  - Demo
  - Usage
  - Logging

components:
  - UIComponent
  - Control
  - PageObject
  - Page
  - TextInput
  - PasswordInput
  - NumberInput
  - DateInput
  - TimeInput
  - Select
  - CheckBox
  - CheckBoxList
  - RadioButton
  - RadioButtonList
  - TextArea
  - Button
  - Link
  - Clickable
  - Content
  - Text
  - H1-H6

exclude:
  - LICENSE
  - README.md
  - atata-framework.github.io.sln
  - compilerconfig.json
  - compilerconfig.json.defaults
  - .gitignore

links:
    atata_github: https://github.com/atata-framework/atata
    atata_nuget: https://www.nuget.org/packages/Atata
    atata_webdriverextras_nuget: https://www.nuget.org/packages/Atata.WebDriverExtras