name: Atata
short_description: "C#/.NET test automation framework"

# Dependencies
markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: false

gems:
  - jekyll-sitemap

# Permalinks
permalink: pretty

author:
  name: Yevgeniy Shunevych
  github: YevgeniyShunevych

baseurl: ""
url: ""

nav_links:
  Getting Started: "getting-started"
  Components: "components"
  Control Search: "control-search"
  Triggers: "triggers"
  #Advanced: "advanced"

getting-started:
  - name: Introduction
  - name: Demo
  - name: Usage
    items:
      - Define Settings
      - Define Page Object Class
      - Implement Test
      - View Log
  - name: Set Up
    items:
      - Driver
      - Driver Configuration
      - Other

components:
  - name: Base
    items:
      - UIComponent
      - Control
      - PageObject
      - Page
      - PopupWindow
  - name: Inputs
    items:
      - TextInput
      - PasswordInput
      - NumberInput
      - DateInput
      - TimeInput
      - CheckBox
      - CheckBoxList
      - RadioButton
      - RadioButtonList
  - name: Select
  - name: TextArea
  - name: Button
  - name: Link
  - name: Clickable
  - name: Table
  - name: Content
    items:
      - Enum Content
      - Text
      - H1-H6
      - Number
      - Currency
      - Date
      - Time
      - DateTime

control-search:
  - name: General
    items:
      - Term
      - Multiple Terms
      - TermMatch
      - TermCase
      - ScopeSource
  - name: Base Attributes
    items:
      - FindAttribute
      - TermFindAttribute
  - name: Find Attributes
    items:
      - FindById
      - FindByName
      - FindByClass
      - FindByXPath
      - FindByCss
      - FindByLabel
      - FindByFieldSet
      - FindByDescriptionTerm
      - FindByContent
      - FindByChildContent
      - FindByAttribute
      - FindByValue
      - FindByContentOrValue
      - FindByPlaceholder
      - FindByTitle
      - FindFirst
      - FindByIndex
      - FindByColumnHeader
      - FindByColumnIndex
  - name: Settings Attributes
    items:
      - FindSettings
      - TermFindSettings
      - ControlFinding

triggers:
  - name: General
    items:
      - Trigger
      - TriggerEvents
      - TriggerPriority
      - TriggerScope
  - name: Verification
    items:
      - VerifyTitle
      - VerifyH1-H6
      - VerifyContent
      - VerifyContentMatches
      - VerifyExists
      - VerifyMissing
  - name: Waiting
    items:
      - Wait
      - WaitForElement
      - WaitForJQueryAjax
  - name: Performing
    items:
      - LogInfo
      - Screenshot
      - CloseAlertBox
      - CloseConfirmBox
      - PressKeys
      - PressEnter
      - PressTab
      - ScrollDown
      - ScrollUp
      - ClickParent
      - HoverParent

exclude:
  - LICENSE
  - README.md
  - atata-framework.github.io.sln
  - compilerconfig.json
  - compilerconfig.json.defaults
  - .gitignore

links:
    atata_github: https://github.com/atata-framework/atata
    atata_nuget: https://www.nuget.org/packages/Atata
    atata_webdriverextras_nuget: https://www.nuget.org/packages/Atata.WebDriverExtras